version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: analytics
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Load init.sql
    networks:
      - backend
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"
  
  authentication:
    build: ./authentication
    networks:
      - backend
    ports:
      - "5000:5000"

  collection:
    build: ./collection
    depends_on:
      - mysql
      - authentication
    networks:
      - backend
    ports:
      - "3000:3000"
  
  results:
    build: ./results
    depends_on:
      - mongodb
      - authentication
    networks:
      - backend
    ports:
      - "4000:4000"

  analysis:
    build: ./analysis
    depends_on:
      - mysql
      - mongodb
    networks:
      - backend
    ports:
      - "6000:6000"

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
