CREATE DATABASE IF NOT EXISTS analytics;

USE analytics;

CREATE TABLE IF NOT EXISTS grades (
  id  AUTO_INCREMENT PRIMARY KEY,
  student_name VARCHAR(255),
  grade INT
);

ALTER TABLE grades ADD COLUMN studentID VARCHAR(255);

